'use client';

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'th' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data
const translations = {
  th: {
    // Navigation
    'nav.home': 'หน้าแรก',
    'nav.products': 'สินค้า',
    'nav.categories': 'หมวดหมู่',
    'nav.deals': 'โปรโมชั่น',
    'nav.about': 'เกี่ยวกับเรา',
    'nav.login': 'เข้าสู่ระบบ',
    'nav.register': 'สมัครสมาชิก',
    'nav.search.placeholder': 'ค้นหาสินค้า...',
    'nav.search.clear': 'ล้างการค้นหา',
    'nav.search.submit': 'ค้นหา',
    
    // Common
    'common.loading': 'กำลังโหลด...',
    'common.error': 'เกิดข้อผิดพลาด',
    'common.retry': 'ลองใหม่',
    'common.back': 'กลับ',
    'common.next': 'ถัดไป',
    'common.previous': 'ก่อนหน้า',
    'common.save': 'บันทึก',
    'common.cancel': 'ยกเลิก',
    'common.confirm': 'ยืนยัน',
    'common.delete': 'ลบ',
    'common.edit': 'แก้ไข',
    'common.view': 'ดู',
    'common.close': 'ปิด',
    
    // Language
    'language.thai': 'ไทย',
    'language.english': 'English',
    'language.switch': 'เปลี่ยนภาษา',
    
    // Pages
    'page.home.title': 'ยินดีต้อนรับสู่ WatcharaBunp',
    'page.home.subtitle': 'ร้านค้าออนไลน์ครบครันสำหรับทุกความต้องการ',
    'page.products.title': 'สินค้าทั้งหมด',
    'page.categories.title': 'หมวดหมู่สินค้า',
    'page.deals.title': 'โปรโมชั่นพิเศษ',
    'page.about.title': 'เกี่ยวกับเรา',
    'page.login.title': 'เข้าสู่ระบบ',
    'page.register.title': 'สมัครสมาชิก',
    
    // Product
    'product.price': 'ราคา',
    'product.addToCart': 'เพิ่มลงตะกร้า',
    'product.outOfStock': 'สินค้าหมด',
    'product.inStock': 'มีสินค้า',
    'product.new': 'ใหม่',
    'product.discount': 'ลด',
    'product.reviews': 'รีวิว',
    
    // Products Page
    'products.title': 'สินค้าทั้งหมด',
    'products.searchResults': 'ผลการค้นหา',
    'products.searchResultsFor': 'พบ {count} สินค้าจากการค้นหา "{query}"',
    'products.subtitle': 'ค้นพบสินค้าคุณภาพดีในราคาที่เหมาะสม จากร้าน WatcharaBunp',
    'products.categories': 'หมวดหมู่',
    'products.priceRange': 'ช่วงราคา',
    'products.quickFilters': 'ตัวกรองด่วน',
    'products.filters': 'ตัวกรอง',
    'products.applyFilters': 'ใช้ตัวกรอง',
    'products.sortBy': 'เรียงตาม',
    'products.found': 'พบ {count} รายการ',
    'products.noResults': 'ไม่พบสินค้า',
    'products.noResultsMessage': 'ลองปรับเปลี่ยนตัวกรองหรือคำค้นหาของคุณ',
    
    // Categories
    'category.all': 'ทั้งหมด',
    'category.clothing': 'เสื้อผ้า',
    'category.electronics': 'อิเล็กทรอนิกส์',
    'category.bags': 'กระเป๋า',
    'category.shoes': 'รองเท้า',
    'category.books': 'หนังสือ',
    'category.stationery': 'เครื่องเขียน',
    'category.home': 'ของใช้ในบ้าน',
    'category.beauty': 'ความงาม',
    
    // Sort Options
    'sort.newest': 'สินค้าใหม่ล่าสุด',
    'sort.priceLow': 'ราคา: ต่ำ → สูง',
    'sort.priceHigh': 'ราคา: สูง → ต่ำ',
    'sort.rating': 'คะแนนสูงสุด',
    'sort.popular': 'ความนิยม',
    
    // Quick Filters
    'filter.newProducts': 'สินค้าใหม่',
    'filter.discounted': 'สินค้าลดราคา',
    'filter.highRating': 'คะแนน 4+ ดาว',
    
    // Categories Page
    'categories.title': 'หมวดหมู่สินค้า',
    'categories.subtitle': 'เลือกช้อปปิ้งตามหมวดหมู่ที่คุณสนใจ พบกับสินค้าคุณภาพดีมากมาย ที่จัดแบ่งไว้อย่างเป็นระบบเพื่อความสะดวกของคุณ',
    'categories.searchPlaceholder': 'ค้นหาหมวดหมู่...',
    'categories.filterAll': 'ทั้งหมด',
    'categories.filterPopular': 'ยอดนิยม',
    'categories.filterHighCount': 'มากกว่า 500 สินค้า',
    'categories.popularTitle': 'หมวดหมู่ยอดนิยม',
    'categories.popularSubtitle': 'หมวดหมู่ที่ได้รับความนิยมสูงสุดจากลูกค้า',
    'categories.allTitle': 'หมวดหมู่ทั้งหมด',
    'categories.filteredTitle': 'หมวดหมู่{filter}',
    'categories.foundCount': 'พบ {count} หมวดหมู่',
    'categories.products': 'สินค้า',
    'categories.popularBadge': 'ยอดนิยม',
    'categories.noResults': 'ไม่พบหมวดหมู่',
    'categories.noResultsMessage': 'ลองค้นหาด้วยคำค้นหาอื่น หรือเลือกตัวกรองใหม่',
    'categories.resetSearch': 'รีเซ็ตการค้นหา',
    'categories.ctaTitle': 'ไม่พบสิ่งที่ต้องการ?',
    'categories.ctaSubtitle': 'ดูสินค้าทั้งหมดของเรา หรือติดต่อทีมงานเพื่อขอคำแนะนำ',
    'categories.viewAllProducts': 'ดูสินค้าทั้งหมด',
    'categories.contactUs': 'ติดต่อเรา',
    
    // Category Names
    'categoryName.clothing': 'เสื้อผ้า',
    'categoryName.electronics': 'อิเล็กทรอนิกส์',
    'categoryName.homeGarden': 'บ้านและสวน',
    'categoryName.beauty': 'ความงาม',
    'categoryName.sports': 'กีฬาและฟิตเนส',
    'categoryName.books': 'หนังสือและสื่อ',
    'categoryName.toys': 'ของเล่นและเกม',
    'categoryName.food': 'อาหารและเครื่องดื่ม',
    'categoryName.automotive': 'รถยนต์และอุปกรณ์',
    'categoryName.stationery': 'เครื่องเขียนและอุปกรณ์สำนักงาน',
    'categoryName.health': 'สุขภาพและยา',
    'categoryName.others': 'อื่นๆ',
    
    // Category Descriptions
    'categoryDesc.clothing': 'เสื้อผ้าแฟชั่นสำหรับทุกเพศทุกวัย',
    'categoryDesc.electronics': 'อุปกรณ์อิเล็กทรอนิกส์และเทคโนโลยี',
    'categoryDesc.homeGarden': 'ของตั้งแต่งบ้านและอุปกรณ์จัดสวน',
    'categoryDesc.beauty': 'เครื่องสำอางและผลิตภัณฑ์ดูแลผิว',
    'categoryDesc.sports': 'อุปกรณ์กีฬาและออกกำลังกาย',
    'categoryDesc.books': 'หนังสือ นิตยสาร และสื่อการเรียนรู้',
    'categoryDesc.toys': 'ของเล่นสำหรับเด็กและเกมต่างๆ',
    'categoryDesc.food': 'อาหารแห้ง ขนม และเครื่องดื่ม',
    'categoryDesc.automotive': 'อุปกรณ์รถยนต์และมอเตอร์ไซค์',
    'categoryDesc.stationery': 'เครื่องเขียนและอุปกรณ์ทำงาน',
    'categoryDesc.health': 'ผลิตภัณฑ์เพื่อสุขภาพและยา',
    'categoryDesc.others': 'สินค้าหมวดหมู่อื่นๆ ที่น่าสนใจ',

    // HomePage specific
    'home.categories.subtitle': 'เลือกช้อปปิ้งตามหมวดหมู่ที่คุณสนใจ',
    'home.categories.clothing': 'เสื้อผ้า',
    'home.categories.electronics': 'อิเล็กทรอนิกส์',
    'home.categories.home': 'บ้านและสวน',
    'home.categories.beauty': 'ความงาม',
    'home.categories.sports': 'กีฬา',
    'home.categories.books': 'หนังสือ',
    'home.categories.toys': 'ของเล่น',
    'home.categories.other': 'อื่นๆ',
    'home.featured.title': 'สินค้าแนะนำ',
    'home.featured.subtitle': 'สินค้าคุณภาพที่ได้รับความนิยมจากลูกค้า',
    'home.featured.sample': 'สินค้าตัวอย่าง',
    'home.featured.description': 'รายละเอียดสินค้าแบบย่อๆ ที่น่าสนใจ',
    'home.features.shipping.title': 'จัดส่งฟรี',
    'home.features.shipping.description': 'จัดส่งฟรีทั่วประเทศ สำหรับคำสั่งซื้อตั้งแต่ 500 บาท',
    'home.features.quality.title': 'รับประกันคุณภาพ',
    'home.features.quality.description': 'สินค้าทุกชิ้นผ่านการคัดสรรอย่างดี พร้อมการรับประกัน',
    'home.features.support.title': 'บริการ 24/7',
    'home.features.support.description': 'ทีมงานพร้อมให้บริการและแก้ไขปัญหาตลอด 24 ชั่วโมง',

    // Deals Page specific
    'deals.breadcrumb.home': 'หน้าแรก',
    'deals.breadcrumb.deals': 'โปรโมชั่น',
    'deals.hero.badge': 'โปรโมชั่นพิเศษ',
    'deals.hero.title1': 'ลดราคาสุดคุ้ม',
    'deals.hero.title2': 'สูงสุด 70%',
    'deals.hero.subtitle': 'ช้อปสินค้าคุณภาพในราคาพิเศษ โปรโมชั่นจำกัดเวลา อย่าพลาดโอกาสดีๆ นี้!',
    'deals.hero.flashSale': '🔥 Flash Sale',
    'deals.hero.viewAll': 'ดูโปรโมชั่นทั้งหมด',
    'deals.flash.badge': 'Flash Sale',
    'deals.flash.title': 'ลดราคาพิเศษ 24 ชั่วโมง',
    'deals.flash.subtitle': 'โปรโมชั่นจำกัดเวลา ลดสูงสุด 70% สำหรับสินค้าเลือกสรร',
    'deals.categories.title': 'เลือกหมวดหมู่',
    'deals.all.title': 'โปรโมชั่นทั้งหมด',
    'deals.all.found': 'พบ {count} โปรโมชั่น',
    'deals.all.foundInCategory': 'ในหมวด{category}',
    'deals.card.sold': 'ขายแล้ว',
    'deals.card.remaining': 'เหลือ',
    'deals.card.timeLeft': 'เหลือเวลา',
    'deals.card.save': 'ประหยัด',
    'deals.card.buyNow': '🔥 ซื้อเลย!',
    'deals.card.addToCart': 'เพิ่มลงตะกร้า',
    'deals.noResults.title': 'ไม่พบโปรโมชั่น',
    'deals.noResults.message': 'ลองเลือกหมวดหมู่อื่น หรือดูโปรโมชั่นทั้งหมด',
    'deals.noResults.viewAll': 'ดูทั้งหมด',
    'deals.categories.all': 'ทั้งหมด',
    'deals.categories.electronics': 'อิเล็กทรอนิกส์',
    'deals.categories.clothing': 'เสื้อผ้า',
    'deals.categories.homeGarden': 'บ้านและสวน',
    'deals.categories.beauty': 'ความงาม',
    'deals.categories.sports': 'กีฬาและฟิตเนส',
    'deals.categories.books': 'หนังสือและสื่อ',

    // About Page specific
    'about.breadcrumb.home': 'หน้าแรก',
    'about.breadcrumb.about': 'เกี่ยวกับเรา',
    'about.hero.title1': 'เกี่ยวกับ',
    'about.hero.title2': 'WatcharaBunp',
    'about.hero.subtitle': 'เราคือร้านค้าออนไลน์ที่มุ่งมั่นให้บริการสินค้าคุณภาพดี ในราคาที่เหมาะสม พร้อมประสบการณ์การช้อปปิ้งที่ดีที่สุดสำหรับลูกค้าทุกท่าน',
    'about.story.title': 'เรื่องราวของเรา',
    'about.story.p1': 'WatcharaBunp เริ่มต้นจากความตั้งใจที่จะนำเสนอสินค้าคุณภาพดี ให้กับลูกค้าในราคาที่เป็นธรรม พร้อมบริการที่เป็นมิตรและน่าเชื่อถือ',
    'about.story.p2': 'ด้วยประสบการณ์กว่า 5 ปีในธุรกิจค้าปลีก เราเข้าใจความต้องการของลูกค้า และมุ่งมั่นที่จะพัฒนาบริการให้ดีขึ้นอย่างต่อเนื่อง',
    'about.story.p3': 'วันนี้ เรามีลูกค้ามากกว่า 50,000 คน และยังคงเติบโตอย่างต่อเนื่อง เพื่อเป็นหนึ่งในร้านค้าออนไลน์ที่ได้รับความไว้วางใจมากที่สุด',
    'about.story.innovation': 'นวัตกรรม',
    'about.story.innovationDesc': 'เทคโนโลยีที่ทันสมัย',
    'about.values.title': 'ค่านิยมของเรา',
    'about.values.subtitle': 'หลักการที่เรายึดถือและนำมาปฏิบัติในการให้บริการลูกค้าทุกท่าน',
    'about.values.quality.title': 'คุณภาพ',
    'about.values.quality.desc': 'สินค้าทุกชิ้นผ่านการคัดสรรอย่างดี เพื่อความพึงพอใจสูงสุด',
    'about.values.price.title': 'ราคาเป็นธรรม',
    'about.values.price.desc': 'มุ่งมั่นเสนอราคาที่เหมาะสม คุ้มค่าสำหรับทุกงบประมาณ',
    'about.values.care.title': 'ใส่ใจลูกค้า',
    'about.values.care.desc': 'บริการด้วยใจ ดูแลลูกค้าทุกท่านเหมือนเป็นครอบครัว',
    'about.values.innovation.title': 'นวัตกรรม',
    'about.values.innovation.desc': 'พัฒนาและปรับปรุงบริการอย่างต่อเนื่อง ให้ทันสมัยเสมอ',
    'about.stats.title': 'ความสำเร็จในตัวเลข',
    'about.stats.subtitle': 'ผลงานที่ภาคภูมิใจและแสดงถึงความไว้วางใจจากลูกค้า',
    'about.stats.customers': 'ลูกค้าที่ไว้วางใจ',
    'about.stats.products': 'สินค้าหลากหลาย',
    'about.stats.satisfaction': 'ความพึงพอใจ',
    'about.stats.experience': 'ปีของประสบการณ์',
    'about.team.title': 'ทีมงานของเรา',
    'about.team.subtitle': 'ทีมงานมืออาชีพที่พร้อมให้บริการและดูแลลูกค้าอย่างใส่ใจ',
    'about.team.founder.name': 'Watchara Bunp.',
    'about.team.founder.position': 'ผู้ก่อตั้ง & CEO',
    'about.team.founder.desc': 'ผู้นำทีมด้วยวิสัยทัศน์และประสบการณ์กว่า 10 ปี',
    'about.team.sales.name': 'Somchai Jaidee',
    'about.team.sales.position': 'ผู้จัดการฝ่ายขาย',
    'about.team.sales.desc': 'เชี่ยวชาญด้านการตลาดและการดูแลลูกค้าสัมพันธ์',
    'about.team.service.name': 'Sukanya Raklukkha',
    'about.team.service.position': 'หัวหน้าฝ่ายบริการลูกค้า',
    'about.team.service.desc': 'ผู้เชี่ยวชาญด้านการบริการและแก้ไขปัญหา',

    // Login Page specific
    'login.title': 'เข้าสู่ระบบ',
    'login.subtitle': 'ยินดีต้อนรับกลับสู่ร้านค้าของเรา',
    'login.email.label': 'อีเมล',
    'login.email.placeholder': 'example@email.com',
    'login.email.required': 'กรุณากรอกอีเมล',
    'login.email.invalid': 'รูปแบบอีเมลไม่ถูกต้อง',
    'login.password.label': 'รหัสผ่าน',
    'login.password.placeholder': '••••••••',
    'login.password.required': 'กรุณากรอกรหัสผ่าน',
    'login.password.minLength': 'รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร',
    'login.rememberMe': 'จดจำฉันไว้',
    'login.forgotPassword': 'ลืมรหัสผ่าน?',
    'login.submit': 'เข้าสู่ระบบ',
    'login.submitting': 'กำลังเข้าสู่ระบบ...',
    'login.success': 'เข้าสู่ระบบสำเร็จ!',
    'login.error.general': 'เกิดข้อผิดพลาด กรุณาลองใหม่อีกครั้ง',
    'login.divider': 'หรือ',
    'login.noAccount': 'ยังไม่มีบัญชี?',
    'login.signUp': 'สมัครสมาชิก',
    'login.backToHome': '← กลับสู่หน้าหลัก',

    // Register Page specific
    'register.title': 'สมัครสมาชิก',
    'register.subtitle': 'เริ่มต้นการช้อปปิ้งกับเรา',
    'register.name.label': 'ชื่อ-นามสกุล',
    'register.name.placeholder': 'กรอกชื่อ-นามสกุล',
    'register.name.required': 'กรุณากรอกชื่อ-นามสกุล',
    'register.name.minLength': 'ชื่อ-นามสกุลต้องมีอย่างน้อย 2 ตัวอักษร',
    'register.email.label': 'อีเมล',
    'register.email.placeholder': 'example@email.com',
    'register.email.required': 'กรุณากรอกอีเมล',
    'register.email.invalid': 'รูปแบบอีเมลไม่ถูกต้อง',
    'register.password.label': 'รหัสผ่าน',
    'register.password.placeholder': 'อย่างน้อย 8 ตัวอักษร',
    'register.password.required': 'กรุณากรอกรหัสผ่าน',
    'register.password.minLength': 'รหัสผ่านต้องมีอย่างน้อย 8 ตัวอักษร',
    'register.password.pattern': 'รหัสผ่านต้องมีตัวอักษรเล็ก ตัวใหญ่ และตัวเลข',
    'register.password.strength': 'ความแข็งแกร่งของรหัสผ่าน:',
    'register.confirmPassword.label': 'ยืนยันรหัสผ่าน',
    'register.confirmPassword.placeholder': 'ยืนยันรหัสผ่านอีกครั้ง',
    'register.confirmPassword.required': 'กรุณายืนยันรหัสผ่าน',
    'register.confirmPassword.mismatch': 'รหัสผ่านไม่ตรงกัน',
    'register.confirmPassword.match': '✓ รหัสผ่านตรงกัน',
    'register.confirmPassword.noMatch': '✗ รหัสผ่านไม่ตรงกัน',
    'register.terms.text': 'ฉันยอมรับ',
    'register.terms.link': 'เงื่อนไขการใช้งาน',
    'register.terms.and': 'และ',
    'register.privacy.link': 'นโยบายความเป็นส่วนตัว',
    'register.terms.required': 'กรุณายอมรับเงื่อนไขการใช้งาน',
    'register.submit': 'สมัครสมาชิก',
    'register.submitting': 'กำลังสมัครสมาชิก...',
    'register.success': 'สมัครสมาชิกสำเร็จ! กรุณาเข้าสู่ระบบ',
    'register.error.general': 'เกิดข้อผิดพลาด กรุณาลองใหม่อีกครั้ง',
    'register.divider': 'หรือ',
    'register.hasAccount': 'มีบัญชีอยู่แล้ว?',
    'register.signIn': 'เข้าสู่ระบบ',
    'register.backToHome': '← กลับสู่หน้าหลัก',

    // Footer specific
    'footer.company.description': 'ร้านค้าออนไลน์ครบครันสำหรับทุกความต้องการ พร้อมส่งมอบประสบการณ์การช้อปปิ้งที่ดีที่สุดให้กับลูกค้า',
    'footer.quickLinks.title': 'ลิงก์ด่วน',
    'footer.quickLinks.allProducts': 'สินค้าทั้งหมด',
    'footer.quickLinks.categories': 'หมวดหมู่สินค้า',
    'footer.quickLinks.deals': 'โปรโมชั่น',
    'footer.quickLinks.newArrivals': 'สินค้าใหม่',
    'footer.quickLinks.bestsellers': 'สินค้าขายดี',
    'footer.customerService.title': 'บริการลูกค้า',
    'footer.customerService.contact': 'ติดต่อเรา',
    'footer.customerService.shipping': 'ข้อมูลการจัดส่ง',
    'footer.customerService.returns': 'นโยบายการคืนสินค้า',
    'footer.customerService.faq': 'คำถามที่พบบ่อย',
    'footer.customerService.sizeGuide': 'คู่มือขนาดสินค้า',
    'footer.newsletter.title': 'รับข่าวสารและโปรโมชั่น',
    'footer.newsletter.description': 'สมัครรับข่าวสารเพื่อไม่พลาดโปรโมชั่นพิเศษ',
    'footer.newsletter.placeholder': 'กรอกอีเมลของคุณ',
    'footer.newsletter.subscribe': 'สมัคร',
    'footer.payment.title': 'ช่องทางการชำระเงิน',
    'footer.copyright': '© 2025 WatcharaBunp. สงวนลิขสิทธิ์ทั้งหมด',
    'footer.legal.privacy': 'นโยบายความเป็นส่วนตัว',
    'footer.legal.terms': 'ข้อกำหนดการใช้งาน',
    'footer.legal.cookies': 'นโยบายคุกกี้',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.categories': 'Categories',
    'nav.deals': 'Deals',
    'nav.about': 'About Us',
    'nav.login': 'Login',
    'nav.register': 'Register',
    'nav.search.placeholder': 'Search products...',
    'nav.search.clear': 'Clear search',
    'nav.search.submit': 'Search',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'An error occurred',
    'common.retry': 'Retry',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.close': 'Close',
    
    // Language
    'language.thai': 'ไทย',
    'language.english': 'English',
    'language.switch': 'Change Language',
    
    // Pages
    'page.home.title': 'Welcome to WatcharaBunp',
    'page.home.subtitle': 'Complete online store for all your needs',
    'page.products.title': 'All Products',
    'page.categories.title': 'Product Categories',
    'page.deals.title': 'Special Deals',
    'page.about.title': 'About Us',
    'page.login.title': 'Login',
    'page.register.title': 'Register',
    
    // Product
    'product.price': 'Price',
    'product.addToCart': 'Add to Cart',
    'product.outOfStock': 'Out of Stock',
    'product.inStock': 'In Stock',
    'product.new': 'New',
    'product.discount': 'Off',
    'product.reviews': 'reviews',
    
    // Products Page
    'products.title': 'All Products',
    'products.searchResults': 'Search Results',
    'products.searchResultsFor': 'Found {count} products for "{query}"',
    'products.subtitle': 'Discover quality products at great prices from WatcharaBunp',
    'products.categories': 'Categories',
    'products.priceRange': 'Price Range',
    'products.quickFilters': 'Quick Filters',
    'products.filters': 'Filters',
    'products.applyFilters': 'Apply Filters',
    'products.sortBy': 'Sort by',
    'products.found': 'Found {count} items',
    'products.noResults': 'No Products Found',
    'products.noResultsMessage': 'Try adjusting your filters or search terms',
    
    // Categories
    'category.all': 'All',
    'category.clothing': 'Clothing',
    'category.electronics': 'Electronics',
    'category.bags': 'Bags',
    'category.shoes': 'Shoes',
    'category.books': 'Books',
    'category.stationery': 'Stationery',
    'category.home': 'Home',
    'category.beauty': 'Beauty',
    
    // Sort Options
    'sort.newest': 'Newest First',
    'sort.priceLow': 'Price: Low → High',
    'sort.priceHigh': 'Price: High → Low',
    'sort.rating': 'Highest Rating',
    'sort.popular': 'Most Popular',
    
    // Quick Filters
    'filter.newProducts': 'New Products',
    'filter.discounted': 'On Sale',
    'filter.highRating': '4+ Stars',
    
    // Categories Page
    'categories.title': 'Product Categories',
    'categories.subtitle': 'Choose to shop by categories that interest you. Discover quality products organized systematically for your convenience.',
    'categories.searchPlaceholder': 'Search categories...',
    'categories.filterAll': 'All',
    'categories.filterPopular': 'Popular',
    'categories.filterHighCount': 'More than 500 products',
    'categories.popularTitle': 'Popular Categories',
    'categories.popularSubtitle': 'Most popular categories among our customers',
    'categories.allTitle': 'All Categories',
    'categories.filteredTitle': '{filter} Categories',
    'categories.foundCount': 'Found {count} categories',
    'categories.products': 'products',
    'categories.popularBadge': 'Popular',
    'categories.noResults': 'No Categories Found',
    'categories.noResultsMessage': 'Try searching with different keywords or select a new filter',
    'categories.resetSearch': 'Reset Search',
    'categories.ctaTitle': "Can't find what you're looking for?",
    'categories.ctaSubtitle': 'Browse all our products or contact our team for recommendations',
    'categories.viewAllProducts': 'View All Products',
    'categories.contactUs': 'Contact Us',
    
    // Category Names
    'categoryName.clothing': 'Clothing',
    'categoryName.electronics': 'Electronics',
    'categoryName.homeGarden': 'Home & Garden',
    'categoryName.beauty': 'Beauty',
    'categoryName.sports': 'Sports & Fitness',
    'categoryName.books': 'Books & Media',
    'categoryName.toys': 'Toys & Games',
    'categoryName.food': 'Food & Beverages',
    'categoryName.automotive': 'Automotive & Parts',
    'categoryName.stationery': 'Stationery & Office Supplies',
    'categoryName.health': 'Health & Medicine',
    'categoryName.others': 'Others',
    
    // Category Descriptions
    'categoryDesc.clothing': 'Fashion clothing for all ages and genders',
    'categoryDesc.electronics': 'Electronic devices and technology products',
    'categoryDesc.homeGarden': 'Home decor and gardening equipment',
    'categoryDesc.beauty': 'Cosmetics and skincare products',
    'categoryDesc.sports': 'Sports and fitness equipment',
    'categoryDesc.books': 'Books, magazines, and learning materials',
    'categoryDesc.toys': 'Toys for children and various games',
    'categoryDesc.food': 'Dried food, snacks, and beverages',
    'categoryDesc.automotive': 'Car and motorcycle equipment',
    'categoryDesc.stationery': 'Stationery and office supplies',
    'categoryDesc.health': 'Health products and medicine',
    'categoryDesc.others': 'Other interesting product categories',

    // HomePage specific
    'home.categories.subtitle': 'Choose to shop by categories that interest you',
    'home.categories.clothing': 'Clothing',
    'home.categories.electronics': 'Electronics',
    'home.categories.home': 'Home & Garden',
    'home.categories.beauty': 'Beauty',
    'home.categories.sports': 'Sports',
    'home.categories.books': 'Books',
    'home.categories.toys': 'Toys',
    'home.categories.other': 'Others',
    'home.featured.title': 'Featured Products',
    'home.featured.subtitle': 'Quality products popular with our customers',
    'home.featured.sample': 'Sample Product',
    'home.featured.description': 'Brief and interesting product description',
    'home.features.shipping.title': 'Free Shipping',
    'home.features.shipping.description': 'Free shipping nationwide for orders over 500 baht',
    'home.features.quality.title': 'Quality Guarantee',
    'home.features.quality.description': 'Every product is carefully selected with warranty included',
    'home.features.support.title': '24/7 Service',
    'home.features.support.description': 'Our team is ready to serve and solve problems 24 hours a day',

    // Deals Page specific
    'deals.breadcrumb.home': 'Home',
    'deals.breadcrumb.deals': 'Deals',
    'deals.hero.badge': 'Special Deals',
    'deals.hero.title1': 'Amazing Discounts',
    'deals.hero.title2': 'Up to 70% Off',
    'deals.hero.subtitle': 'Shop quality products at special prices. Limited time offers - don\'t miss out!',
    'deals.hero.flashSale': '🔥 Flash Sale',
    'deals.hero.viewAll': 'View All Deals',
    'deals.flash.badge': 'Flash Sale',
    'deals.flash.title': '24-Hour Special Discounts',
    'deals.flash.subtitle': 'Limited time offers with up to 70% off selected items',
    'deals.categories.title': 'Select Category',
    'deals.all.title': 'All Deals',
    'deals.all.found': 'Found {count} deals',
    'deals.all.foundInCategory': 'in {category}',
    'deals.card.sold': 'Sold',
    'deals.card.remaining': 'Left',
    'deals.card.timeLeft': 'Time Left',
    'deals.card.save': 'Save',
    'deals.card.buyNow': '🔥 Buy Now!',
    'deals.card.addToCart': 'Add to Cart',
    'deals.noResults.title': 'No Deals Found',
    'deals.noResults.message': 'Try selecting another category or view all deals',
    'deals.noResults.viewAll': 'View All',
    'deals.categories.all': 'All',
    'deals.categories.electronics': 'Electronics',
    'deals.categories.clothing': 'Clothing',
    'deals.categories.homeGarden': 'Home & Garden',
    'deals.categories.beauty': 'Beauty',
    'deals.categories.sports': 'Sports & Fitness',
    'deals.categories.books': 'Books & Media',

    // About Page specific
    'about.breadcrumb.home': 'Home',
    'about.breadcrumb.about': 'About Us',
    'about.hero.title1': 'About',
    'about.hero.title2': 'WatcharaBunp',
    'about.hero.subtitle': 'We are an online store committed to providing quality products at reasonable prices, with the best shopping experience for all our customers',
    'about.story.title': 'Our Story',
    'about.story.p1': 'WatcharaBunp started with the intention to offer quality products to customers at fair prices, with friendly and trustworthy service',
    'about.story.p2': 'With over 5 years of experience in retail business, we understand customer needs and are committed to continuously improving our services',
    'about.story.p3': 'Today, we have more than 50,000 customers and continue to grow to become one of the most trusted online stores',
    'about.story.innovation': 'Innovation',
    'about.story.innovationDesc': 'Modern Technology',
    'about.values.title': 'Our Values',
    'about.values.subtitle': 'The principles we uphold and apply in serving all our customers',
    'about.values.quality.title': 'Quality',
    'about.values.quality.desc': 'Every product is carefully selected for maximum satisfaction',
    'about.values.price.title': 'Fair Pricing',
    'about.values.price.desc': 'Committed to offering reasonable prices, value for every budget',
    'about.values.care.title': 'Customer Care',
    'about.values.care.desc': 'Service with heart, caring for every customer like family',
    'about.values.innovation.title': 'Innovation',
    'about.values.innovation.desc': 'Continuously develop and improve services to stay modern',
    'about.stats.title': 'Success in Numbers',
    'about.stats.subtitle': 'Achievements we\'re proud of and that show customer trust',
    'about.stats.customers': 'Trusted Customers',
    'about.stats.products': 'Diverse Products',
    'about.stats.satisfaction': 'Satisfaction',
    'about.stats.experience': 'Years of Experience',
    'about.team.title': 'Our Team',
    'about.team.subtitle': 'Professional team ready to serve and care for customers attentively',
    'about.team.founder.name': 'Watchara Bunp.',
    'about.team.founder.position': 'Founder & CEO',
    'about.team.founder.desc': 'Team leader with vision and over 10 years of experience',
    'about.team.sales.name': 'Somchai Jaidee',
    'about.team.sales.position': 'Sales Manager',
    'about.team.sales.desc': 'Expert in marketing and customer relationship management',
    'about.team.service.name': 'Sukanya Raklukkha',
    'about.team.service.position': 'Head of Customer Service',
    'about.team.service.desc': 'Expert in service and problem solving',

    // Login Page specific
    'login.title': 'Login',
    'login.subtitle': 'Welcome back to our store',
    'login.email.label': 'Email',
    'login.email.placeholder': 'example@email.com',
    'login.email.required': 'Please enter your email',
    'login.email.invalid': 'Invalid email format',
    'login.password.label': 'Password',
    'login.password.placeholder': '••••••••',
    'login.password.required': 'Please enter your password',
    'login.password.minLength': 'Password must be at least 6 characters',
    'login.rememberMe': 'Remember me',
    'login.forgotPassword': 'Forgot password?',
    'login.submit': 'Login',
    'login.submitting': 'Logging in...',
    'login.success': 'Login successful!',
    'login.error.general': 'An error occurred. Please try again',
    'login.divider': 'or',
    'login.noAccount': "Don't have an account?",
    'login.signUp': 'Sign up',
    'login.backToHome': '← Back to home',

    // Register Page specific
    'register.title': 'Register',
    'register.subtitle': 'Start shopping with us',
    'register.name.label': 'Full Name',
    'register.name.placeholder': 'Enter your full name',
    'register.name.required': 'Please enter your full name',
    'register.name.minLength': 'Full name must be at least 2 characters',
    'register.email.label': 'Email',
    'register.email.placeholder': 'example@email.com',
    'register.email.required': 'Please enter your email',
    'register.email.invalid': 'Invalid email format',
    'register.password.label': 'Password',
    'register.password.placeholder': 'At least 8 characters',
    'register.password.required': 'Please enter a password',
    'register.password.minLength': 'Password must be at least 8 characters',
    'register.password.pattern': 'Password must contain lowercase, uppercase, and numbers',
    'register.password.strength': 'Password strength:',
    'register.confirmPassword.label': 'Confirm Password',
    'register.confirmPassword.placeholder': 'Confirm your password',
    'register.confirmPassword.required': 'Please confirm your password',
    'register.confirmPassword.mismatch': 'Passwords do not match',
    'register.confirmPassword.match': '✓ Passwords match',
    'register.confirmPassword.noMatch': '✗ Passwords do not match',
    'register.terms.text': 'I accept the',
    'register.terms.link': 'Terms of Service',
    'register.terms.and': 'and',
    'register.privacy.link': 'Privacy Policy',
    'register.terms.required': 'Please accept the Terms of Service',
    'register.submit': 'Register',
    'register.submitting': 'Creating account...',
    'register.success': 'Registration successful! Please log in',
    'register.error.general': 'An error occurred. Please try again',
    'register.divider': 'or',
    'register.hasAccount': 'Already have an account?',
    'register.signIn': 'Sign in',
    'register.backToHome': '← Back to home',

    // Footer specific
    'footer.company.description': 'Complete online store for all your needs, delivering the best shopping experience to our customers',
    'footer.quickLinks.title': 'Quick Links',
    'footer.quickLinks.allProducts': 'All Products',
    'footer.quickLinks.categories': 'Categories',
    'footer.quickLinks.deals': 'Deals',
    'footer.quickLinks.newArrivals': 'New Arrivals',
    'footer.quickLinks.bestsellers': 'Best Sellers',
    'footer.customerService.title': 'Customer Service',
    'footer.customerService.contact': 'Contact Us',
    'footer.customerService.shipping': 'Shipping Information',
    'footer.customerService.returns': 'Return Policy',
    'footer.customerService.faq': 'FAQ',
    'footer.customerService.sizeGuide': 'Size Guide',
    'footer.newsletter.title': 'Newsletter & Promotions',
    'footer.newsletter.description': 'Subscribe to our newsletter to not miss special promotions',
    'footer.newsletter.placeholder': 'Enter your email',
    'footer.newsletter.subscribe': 'Subscribe',
    'footer.payment.title': 'Payment Methods',
    'footer.copyright': '© 2025 WatcharaBunp. All rights reserved',
    'footer.legal.privacy': 'Privacy Policy',
    'footer.legal.terms': 'Terms of Service',
    'footer.legal.cookies': 'Cookie Policy',
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguageState] = useState<Language>('th');
  const [isClient, setIsClient] = useState(false);

  // Load language from localStorage on mount (only on client side)
  useEffect(() => {
    setIsClient(true);
    if (typeof window !== 'undefined') {
      const savedLanguage = localStorage.getItem('language') as Language;
      if (savedLanguage && (savedLanguage === 'th' || savedLanguage === 'en')) {
        setLanguageState(savedLanguage);
      }
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', lang);
    }
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
